Simulation = "DebianUpdateOneClient"
Servers = 4
Bf = 2
Rounds = 20
CloseWait = 6000
Height = 10
Base = 4
RunWait = 3600
Hosts = 4
Delay = 50
Snapshots = "Debian-testing"

NumberOfInstalledPackages, NumberOfPackagesInRepo
1, 10
1, 100
1, 1000
1, 10000
1, 52000
